<?php
/**
 * Created by PhpStorm.
 * User: toby
 * Date: 27/01/15
 * Time: 13:40
 */

namespace FreeAgent\Exception\Module;


use FreeAgent\Module\Module;

class ModuleAlreadyRegisteredException extends ModuleException
{
    /**
     * Builds exception and sets default message
     *
     * @param Module $module
     * @param string $message
     * @param int $code
     * @param null $previousException
     *
     * @return static
     */
    public static function create(Module $module, $message = '', $code = 0, $previousException = null)
    {
        if (empty($message)) {
            $message = "Module {$module->getName()} is already registered";
        }

        return parent::create($module, $message, $code, $previousException); // TODO: Change the autogenerated stub
    }
}